access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
spring:
  data:
    mongodb:

      uri: mongodb+srv://ravishka99:Pravindika99@pafproject.8v4lkrc.mongodb.net/foodiesdb?retryWrites=true&w=majority

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8090